import type { Metadata } from "next";
import { NextFont } from 'next/dist/compiled/@next/font';
const myAdobeFont = {
  src: 'https://use.typekit.net/akc6vgu.css',
};
import "./globals.css";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});*/

{/* 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/akc6vgu.css" />
      </head>
      {children}
    </html>
  );
}
