import type { Metadata } from "next";
import { NextFont } from 'next/dist/compiled/@next/font';
// const myAdobeFont = {
//   src: 'https://use.typekit.net/fqu4lqa.css',
// };
import "./globals.css";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});*/

/* 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <title>タイトル</title>
        <meta name="description" content="説明"></meta>
        <link rel="stylesheet" href="https://use.typekit.net/psv7toa.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
      </head>
        {children}
    </html>
  );
}
